apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.adminer.name }}"
  namespace: {{ .Values.php.namespace }}
  labels:
    app: {{ .Values.adminer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.adminer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminer.name }}
    spec:
      containers:
      - name: {{ .Values.adminer.name }}
        image: "{{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag }}"
        imagePullPolicy: {{ .Values.adminer.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.adminer.port }}