apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Values.db.name }}-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.credentials.rootPassword | b64enc | quote }} #cm9vdA==
  MYSQL_DATABASE: {{ .Values.db.credentials.database | b64enc | quote }} #cmVmYWN0b3JpYW4=
  MYSQL_USER: {{ .Values.db.credentials.user | b64enc | quote }} #cmVmYWN0b3JpYW4=
  MYSQL_PASSWORD: {{ .Values.db.credentials.password | b64enc | quote }} #cmVmYWN0b3JpYW4=
