apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-{{ .Values.db.name }}-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: cmVmYWN0b3JpYW4=
  MYSQL_USER: cmVmYWN0b3JpYW4=
  MYSQL_PASSWORD: cmVmYWN0b3JpYW4=
