apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "charts.fullname" . }}-grafana-datasource"
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://{{ include "charts.fullname" . }}-prometheus:9090
        access: proxy
        isDefault: false

