apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.phpmyadmin.name }}"
  labels:
    app: {{ .Values.phpmyadmin.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.phpmyadmin.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.phpmyadmin.name }}
    spec:
      initContainers:
      - name: fix-sessions-permissions
        image: "{{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: 
        - |
          echo "Waiting for database to be ready..." && \
          apt-get update && apt-get install -y default-mysql-client && \
          until mysqladmin ping -h {{ .Release.Name }}-db --silent; do
            sleep 2;
            echo "Still waiting for database..."; 
          done;

          echo "Database is ready!" && \

          chmod 777 /sessions
        volumeMounts:
        - name: phpmyadmin-sessions
          mountPath: /sessions
      containers:
      - name: phpmyadmin
        image: "{{ .Values.phpmyadmin.image.repository }}:{{ .Values.phpmyadmin.image.tag }}"
        imagePullPolicy: {{ .Values.phpmyadmin.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.phpmyadmin.port }}
        env:
        - name: PMA_HOST
          value: "{{ .Values.phpmyadmin.environment.PMA_HOST }}"
        - name: PMA_PORT
          value: "{{ .Values.phpmyadmin.environment.PMA_PORT }}"
        - name: PMA_ARBITRARY
          value: "{{ .Values.phpmyadmin.environment.PMA_ARBITRARY }}"
        volumeMounts:
        - name: phpmyadmin-sessions
          mountPath: /sessions
      volumes:
      - name: phpmyadmin-sessions
        emptyDir: {}