apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.nginx.name }}"
  namespace: {{ .Values.php.namespace }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
      - name: {{ .Values.nginx.name }}
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: "{{ .Values.nginx.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.nginx.port }}
        volumeMounts:
        - name: {{ .Values.nginx.volumen.name }} #nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-main-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: project-code
          mountPath: /var/www
        # Esperar a que se despliegue el php antes de arrancar  
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - test -f /var/www/public/index.php
          initialDelaySeconds: {{ .Values.nginx.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.nginx.readiness.periodSeconds }}
      volumes:
      - name: {{ .Values.nginx.volumen.name }}
        configMap:
          name: "{{ .Release.Name }}-{{ .Values.configmap.default}}"
      - name: nginx-main-config
        configMap:
          name: "{{ .Release.Name }}-{{ .Values.configmap.nginx }}"
      - name: project-code
        persistentVolumeClaim:
          claimName: {{ .Values.php.pvc.name }}
