apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.nginx.name }}"
  namespace: {{ .Values.php.namespace }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.nginx.port }}
    targetPort: {{ .Values.nginx.port }}
  selector:
    app: {{ .Values.nginx.name }}
