apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.php.pvc.name }}
  namespace: {{ .Values.php.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.php.pvc.storage }}