apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "charts.fullname" . }}-prometheus"
  namespace: {{ .Values.php.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "charts.name" . }}"
      component: prometheus
  template:
    metadata:
      labels:
        app: "{{ include "charts.name" . }}"
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: "{{ include "charts.fullname" . }}-prometheus-config"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "charts.fullname" . }}-prometheus"
  namespace: {{ .Values.php.namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  selector:
    app: "{{ include "charts.name" . }}"
    component: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
