apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "charts.fullname" . }}-prometheus-config"
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - 'laravel-mysql-charts-node-exporter.default.svc.cluster.local:9100'

