# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

####################################################################################################
# PHP
####################################################################################################
php:
  namespace: laravel-mysql
  name: php
  image:
    repository: bryyyan/practica-final
    tag: "1.2"
    pullPolicy: IfNotPresent
  port: 9000 # Cambiar el puerto para que coincida con default-configmap
  initcontainer:
    name: copy-data
  resources:
    requests:
      cpu: "100m"       # CPU mínima solicitada
      memory: "128Mi"   # Memoria mínima solicitada
    limits:
      cpu: "500m"       # CPU máxima permitida
      memory: "256Mi"   # Memoria máxima permitida  
  readiness:
    initialDelaySeconds: 30
    periodSeconds: 15
  liveness:
    initialDelaySeconds: 45
    periodSeconds: 15 
  volumen:
    name: php-code
  pvc:
    name: php-storage
    storage: 1Gi # Modificar el tamaño del pvc en caso de ser necesario 

####################################################################################################
# Nginx
####################################################################################################    

nginx:
  name: nginx
  image:
    repository: nginx
    tag: latest
    pullPolicy: IfNotPresent
  volumen:
    name: nginx-config  
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5    
  port: 80

configmap:
  nginx: nginx-main-config  
  default: default-config

####################################################################################################
# DATABASE (MySQL)
####################################################################################################

db:
  name: db
  image:
    repository: mysql
    tag: "8.1"
    pullPolicy: IfNotPresent
  port: 3306
  volumen:
    name: db-data
  pvc:
    name: mysql-data
    storage: 5Gi # Modificar el tamaño del pvc en caso de ser necesario
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    successThreshold: 1
    failureThreshold: 3
  secrets:
    name: secret   

####################################################################################################
# phpMyAdmin
####################################################################################################

phpmyadmin:
  name: phpmyadmin
  image:
    repository: phpmyadmin/phpmyadmin
    tag: latest
    pullPolicy: IfNotPresent
  port: 80
  environment:
    PMA_HOST: db
    PMA_PORT: 3306
    PMA_ARBITRARY: 1

####################################################################################################
# Adminer
####################################################################################################

adminer:
  name: adminer
  image:
    repository: adminer
    tag: latest
    pullPolicy: IfNotPresent
  port: 8080

####################################################################################################
# Ingress
####################################################################################################
  
ingress:
  name: ingress
  enabled: true
  host: practica.local
  paths:
    grafana: /grafana
    prometheus: /prometheus

####################################################################################################
# HPA
####################################################################################################  
hpa:
  name: hpa
  minReplicas: 1
  maxReplicas: 5
  resource:
    name: cpu
    utilization: 50 # Escalar si el uso promedio de CPU supera el %

####################################################################################################
# Prometheus-Grafana
#################################################################################################### 
prometheus:
  enabled: true
grafana:
  enabled: true
nodeExporter:
  enabled: true