name: release-build

on:
  # Este workflow se ejecutará automáticamente cuando el workflow "test" se complete en la rama principal
  workflow_run:
    workflows:
    - "test"
    branches: [ main ]
    types:
      - completed

permissions:
  # Permisos necesarios para escribir contenido, paquetes, y leer issues y pull requests
  contents: write
  packages: write
  issues: read
  pull-requests: read

jobs:
  semantic-release:
     # Este job solo se ejecuta si el workflow previo fue exitoso y no incluye mensajes específicos de release en los commits
    if: "${{ github.event.workflow_run.conclusion == 'success' && !contains(github.event.commits[0].message, 'chore(release):') }}"
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      # Clonar el repositorio
      - name: Checkout
        uses: actions/checkout@v4   

      # Obtener el historial completo del repositorio  
      - name: Unshallow
        run: git fetch --prune --unshallow  
     
      # Restaurar caché para yq y helm-docs
      - name: Restore Cache for Tools
        uses: actions/cache@v3
        with:
          path: /usr/local/bin
          key: tools-cache-${{ runner.os }}-yq-${{ env.YQ_VERSION }}-helm-docs-${{ env.HELM_DOCS_VERSION }}
          restore-keys: |
            tools-cache-${{ runner.os }}-        

      # Instalar jq, una utilidad para manipular JSON desde la línea de comandos  
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Configurar Node.js con caché para dependencias npm  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Configurar yq, una herramienta para manipular YAML    
      - name: Setup yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
        env:
          YQ_VERSION: "v4.43.1"                  
      
      # Configurar Helm para manejar charts    
      - uses: azure/setup-helm@v4
        with:
          version: '3.16.2'
      
      # Configurar helm-docs para generar documentación de Helm Charts    
      - name: Setup helm-docs
        run: |
          mkdir /tmp/helm-docs
          wget -qO /tmp/helm-docs/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz https://github.com/norwoodj/helm-docs/releases/download/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz
          tar -xf /tmp/helm-docs/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.tar.gz -C /tmp/helm-docs
          sudo mv /tmp/helm-docs/helm-docs /usr/local/bin/helm-docs
          sudo chmod +x /usr/local/bin/helm-docs
        env:
          HELM_DOCS_VERSION: "1.5.0"
  
      # Crear un archivo vacío para almacenar la versión generada por semantic-release    
      - name: Create empty semantic_release_version.txt file
        run: touch semantic_release_version.txt
  
      # Ejecutar semantic-release para generar versiones  
      - name: Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --debug | tee semantic_release_output.txt

          # Si Semantic Release no genera una nueva versión, capturamos la última versión existente
          if grep -q "There are no relevant changes, so no new version is released" semantic_release_output.txt; then
            echo "No new version generated. Fetching the latest version tag."
            VERSION=$(git describe --tags --abbrev=0)
          else
            # Extrae la versión publicada por semantic-release
            VERSION=$(grep -oP '(?<=Published release ).*' semantic_release_output.txt)
            echo "$VERSION" > semantic_release_version.txt
          fi  

      # Verificar el contenido del archivo de versión generado    
      - name: Debug semantic_release_version.txt
        run: |
          ls -l semantic_release_version.txt
          cat semantic_release_version.txt || echo "File is empty or does not exist"

      # Obtener la versión generada y almacenarla en un entorno    
      - name: Get the version
        id: get_version
        run: |
          if [ -s semantic_release_version.txt ]; then
            VERSION=$(cat semantic_release_version.txt)
            echo "Version found: $VERSION"
            echo VERSION=$VERSION >> $GITHUB_ENV
          else  
            echo "No version generated"
            exit 1
          fi  
      
      # Configurar QEMU para construir imágenes Docker multiplataforma      
      - name: Set up QEMU
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-qemu-action@v3   
        
      # Configurar Docker Buildx para construir imágenes multiplataforma  
      - name: Set up Docker Buildx
        if: ${{ env.VERSION != '' }}
        uses: docker/setup-buildx-action@v3

      # Iniciar sesión en el contenedor del registro GHCR 
      - name: Docker Login in GHCR
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Iniciar sesión en Docker Hub    
      - name: Login to Docker Hub
        if: ${{ env.VERSION != '' }}
        uses: docker/login-action@v3
        id: configure-login-dockerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Obtener el nombre base del repositorio    
      - id: repo-basename
        run: |
          echo "value=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
        shell: bash
      
      # Generar metadatos de Docker para etiquetas y nombres de imagen  
      - name: Docker meta
        if: ${{ env.VERSION != '' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo-basename.outputs.value }}
            ghcr.io/${{ github.repository }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.repo-basename.outputs.value }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            #type=semver,pattern={{version}},value=${{ env.VERSION }}

      # Depurar los metadatos generados      
      - name: Debug Docker metadata
        run: |
            echo "Tags: ${{ steps.meta.outputs.tags }}"
            echo "Labels: ${{ steps.meta.outputs.labels }}"            

      # Construir y subir la imagen Docker      
      - name: Build and push Docker image
        if: ${{ env.VERSION != '' }}
        uses: docker/build-push-action@v6
        with:
          context: . # Contexto de construcción
          file: ./Dockerfile # Ruta al Dockerfile
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      # Actualizar el archivo values.yaml del Helm Chart con la nueva versión    
      - name: Update helm chart files to latest version
        if: ${{ env.VERSION != '' }}
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository }}" yq -i '.image.repository = strenv(IMAGE_NAME)' ./charts/values.yaml

      # Empaquetar el Helm Chart con la nueva versión    
      - name: Package helm chart with new version
        if: ${{ env.VERSION != '' }}
        run: |
          helm package ./charts -d /tmp

      # Subir el paquete del Helm Chart como artefacto    
      - name: Upload helm package chart with new version
        if: ${{ env.VERSION != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: helm_package_${{ env.VERSION }}
          path: /tmp/practica-final-${{ env.VERSION }}.tgz